# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setMaximumSize(QtCore.QSize(600, 500))
        Form.setStyleSheet("* {font-size: 20px;}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_name = QtWidgets.QLineEdit(Form)
        self.input_name.setObjectName("input_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_name)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.input_degree = QtWidgets.QComboBox(Form)
        self.input_degree.setObjectName("input_degree")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_degree)
        self.rb2 = QtWidgets.QRadioButton(Form)
        self.rb2.setObjectName("rb2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rb2)
        self.rb1 = QtWidgets.QRadioButton(Form)
        self.rb1.setObjectName("rb1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rb1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.input_price = QtWidgets.QLineEdit(Form)
        self.input_price.setObjectName("input_price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_price)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.input_v = QtWidgets.QLineEdit(Form)
        self.input_v.setObjectName("input_v")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.input_v)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_description = QtWidgets.QPlainTextEdit(Form)
        self.input_description.setObjectName("input_description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_description)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 2)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setMinimumSize(QtCore.QSize(200, 0))
        self.btn.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btn.setObjectName("btn")
        self.gridLayout.addWidget(self.btn, 1, 1, 1, 1)
        self.error_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.error_lbl.setFont(font)
        self.error_lbl.setStyleSheet("color: red; font-weight: bold;")
        self.error_lbl.setText("")
        self.error_lbl.setObjectName("error_lbl")
        self.gridLayout.addWidget(self.error_lbl, 2, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Название"))
        self.label_5.setText(_translate("Form", "Степень обжарки"))
        self.rb2.setText(_translate("Form", "В зёрнах"))
        self.rb1.setText(_translate("Form", "Молотый"))
        self.label_2.setText(_translate("Form", "Описание вкуса"))
        self.label_4.setText(_translate("Form", "Цена"))
        self.label.setText(_translate("Form", "Объём упаковки"))
        self.btn.setText(_translate("Form", "Добавить"))
